Greeting.create(greeting: "Good morning")
Greeting.create(greeting: "How do you do?")
Greeting.create(greeting: "Nice to meet you")
Greeting.create(greeting: "How have you been?")
Greeting.create(greeting: "Hey!")